### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by umgustavo** [DashCruft-Nation/lazap#17]
### Hey!

Do you guys approve use linting on this project (prettier)? 
From what I checked, I saw that there is a mixture of tabs and 4-width spaces, and other things too.
With linting we can set a pattern for the code.

In my fork I'm also restructuring the project and I've already added linting:
```py
📂 lazap
├─ 📂 src
│  ├─ 🎨 assets
│  │  ├─ ✒️ fonts
│  │  │    ...
│  │  └─ 📸 img
│  │       ...
│  ├─ 📂 main
│  │  └─ 📄 index.js # Project's main file
│  └─ 📂 renderer
│     ├─ 📂 css
│     │    ...
│     ├─ 📂 js
│     │  ├─ 📂 launchers
│     │  │    ...
│     │  ├─ 📂 login
│     │  │    ...
│     │  ├─ 📄 functions.js
│     │  ├─ 📄 ipc.js
│     │  └─ 📄 listeners.js
│     ├─ 📄 index.html
│     └─ 📄 login.html
└─ 📂 storage
   └─ 📄 userprofile.json
```

I just want your approval/discuss before making a pull request :)

**Comment by DashCruft** [comment]
Hello Gustavo,

Yes we do. Go on and create a pull request and I'll take a look at it.
I like the example layout!

Thanks for your work and effort in general for this repository <3
