### ISSUE TITLE
Can not Sign up 

### ISSUE THREAD

**Issue by Slimo578** [DashCruft-Nation/lazap#23]
I downloaded Lazap and wantes to sign up so after I put in the information and press sign up there comes this alert and it says: 
Something went wrong while trying to create an account! Possible Issues: You are offline, API was down, Unable to reach the API

**Comment by DashCruft** [comment]
Hey @Slimo578 

Thank you for opening a issue and using Lazap!
Sadly, the login/sign up system is not going to be our priority to do. Simply just continue using lazap by clicking on the ocean blue button on top!
