### ISSUE TITLE
Electron frame thing for macOS

### ISSUE THREAD

**Issue by ChaoticNebula5** [DashCruft-Nation/lazap#4]
If we basically have the inbuilt frame set to true for macOS users, there's no lag in maximising and minimizing.

So you basically do 
`app.on('ready', () => {
    const mainWindow = new electron.BrowserWindow({
        width: 1100,
        height: 580,
        minWidth: 850,
        minHeight: 450,
        resizable: true,
        frame: true,
        show: false,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
        },
    });`

Idk how you gonna detect systems but 👌

and remove these lines
`<div class="titlebar">
        <div class="titlebar-icons d-flex justify-content-end">
            <img src="../img/circle.png" onclick="min_window()" class="titlebar-min mx-1" width="17" height="17">
            <img src="../img/circle.png" onclick="max_window()" class="titlebar-max mx-1" width="17" height="17">
            <img src="../img/circle.png" onclick="close_window()" class="titlebar-exit mx-1" width="17" height="17">
        </div>
    </div>`

**Comment by ChaoticNebula5** [comment]
Oh and remove these lines `
<div class="titlebar">
        <div class="titlebar-icons d-flex justify-content-end">
            <img src="../img/circle.png" onclick="min_window()" class="titlebar-min mx-1" width="17" height="17">
            <img src="../img/circle.png" onclick="max_window()" class="titlebar-max mx-1" width="17" height="17">
            <img src="../img/circle.png" onclick="close_window()" class="titlebar-exit mx-1" width="17" height="17">
        </div>
    </div>
`

**Comment by DashCruft** [comment]
Thank you for the report.

This issue is resolved in bdf88df <3
