### ISSUE TITLE
Clicking the pfp crashes the app

### ISSUE THREAD

**Issue by Rachniotov** [DashCruft-Nation/lazap#5]
I tried changing pfp but when i clicked the predefined pfp, the app crashed with a SIGTRAP signal.

**Comment by DashCruft** [comment]
Hey Rach,

Could you show me a step by step of what you have done when this happened? Maybe a picture too with the error showing?

Thanks! DashCruft

**Comment by Rachniotov** [comment]
Steps to replicate: 
1. Launch the app using `npm start`.
2. Click the pfp on the top left, the app crashes.

Im on linux btw.
This is the error which appears in the console as soon as you start the app
![image](https://user-images.githubusercontent.com/71971848/142794235-e211e360-4643-4abc-b745-20f07f3f14b8.png)
There was no error in the console when the app was crashing but after the crash in the terminal it said
![image](https://user-images.githubusercontent.com/71971848/142794374-7eda1eb6-0982-4026-967e-0bd6d0705b49.png)

**Comment by DashCruft** [comment]
Just committed d10515c into nightly branch.

All startup errors should be solved. However, I'm not sure it fixes the crash you get.

Have you tried deleting your `node_modules` folder, `package-lock.json` file and then doing `npm i`?

**Comment by DashCruft** [comment]
Update: 16cb960 reverts the Content-Security-Policy since it prevents the user to manually set their profile picture

**Comment by Rachniotov** [comment]
Look like that fixed it! We can change the pfp normally
![image](https://user-images.githubusercontent.com/71971848/142795510-13636e52-b8a8-420e-bec7-e386208bcad4.png)
